# -*- coding: utf-8 -*-
"""fibo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbph2FWkP9x9On5NnOKV1XFOM9kz7qIw
"""

n=int(input("Enter the number of terms:"))
a,b=0,1
print("Fibonacci Series:")
for i in range(n):
  print(a, end=" ")
  a, b=b ,a+b
