# -*- coding: utf-8 -*-
"""positive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbph2FWkP9x9On5NnOKV1XFOM9kz7qIw
"""

print("Hello,World!!")

# Input lists
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# Printing positive numbers from list1
print("Output:", ", ".join(str(num) for num in list1 if num > 0))

# Printing positive numbers from list2
positive_numbers = [num for num in list2 if num > 0]
print("Output:", positive_numbers)