# -*- coding: utf-8 -*-
"""sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbph2FWkP9x9On5NnOKV1XFOM9kz7qIw
"""

print("Hello,World!!")

# Input lists
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# Printing positive numbers from list1
print("Output:", ", ".join(str(num) for num in list1 if num > 0))

# Printing positive numbers from list2
positive_numbers = [num for num in list2 if num > 0]
print("Output:", positive_numbers)

# Define two sets
E = {0, 2, 4, 6, 8}
N = {1, 2, 3, 4, 5}

# Set operations
union_set = E.union(N)
intersection_set = E.intersection(N)
difference_set = E.difference(N)
symmetric_difference_set = E.symmetric_difference(N)

# Output
print("Union of E and N is", union_set)
print("Intersection of E and N is", intersection_set)
print("Difference of E and N is", difference_set)
print("Symmetric difference of E and N is", symmetric_difference_set)