# -*- coding: utf-8 -*-
"""simple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbph2FWkP9x9On5NnOKV1XFOM9kz7qIw
"""

print("Hello,World!!")